name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run : export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH && ./main
    
#    - name: Doxygen Action
#      uses: mattnotmitt/doxygen-action@1.9.1
  build_centos-latest:
    runs-on: ubuntu-latest
    container: 'centos:latest'
    steps:
    - uses: actions/checkout@v2
    - name: prerequisits
      run: yum install -y git make gcc-c++ zlib-devel dialog
    - name: make
      run: make
    - name: test
      run : export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH && ./main
