name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
#    - name: Doxygen Action
#      uses: mattnotmitt/doxygen-action@1.9.1
  build2:
    runs-on: ubuntu-latest
    container: 'centos:latest'
    steps:
    - uses: actions/checkout@v2
    - name: prerequisits
      run: yum install -y git make gcc-c++ dialog
    - name: make
      run: make

